Repository knit-pk/api-v1-php, pull requests merged in 2018-02, with the labels that each got.

#39 Feature/enable graphql
  composer.json
  composer.lock
  config/packages/api_platform.yaml
  phpstan.neon
  symfony.lock
Labels: api-platform, feature

#45 Feature/travis deploy
  .travis.yml
  composer.json
  config/services.yaml
  deploy/mydevil-deploy.sh
  deploy/mydevil-post-deploy.sh
  deploy/mydevil.tar.enc
Labels: api-platform, feature

#44 Use new interface for filters
  src/Swagger/Filter/SwaggerBooleanFilter.php
  src/Swagger/Filter/SwaggerGroupFilter.php
  src/Swagger/Filter/SwaggerSearchFilter.php
Labels: api-platform, bug

#46 Feature/filters test
  .env.test
  .gitignore
  .travis.yml
  README.md
  behat.yml.dist
  composer.json
  composer.lock
  config/services.yaml
  config/services_test.yaml
  features/bootstrap/FeatureContext.php
  features/bootstrap/JsonContext.php
  features/demo.feature
  features/filters.feature
  src/Entity/Article.php
Labels: tests

#48 Feature/docker php pm
  README.md
  composer.json
  composer.lock
  docker-compose.yml
  docker/varnish/conf/default.vcl
Labels: docker, feature

#49 Feature/add tests
  .gitignore
  .travis.yml
  composer.json
  composer.lock
  src/Action/Image/ImageUploadAction.php
  src/Action/Thought/AddThoughtAction.php
  src/Entity/Article.php
  src/Entity/Comment.php
  src/Security/User/JWTUser.php
  src/Security/UserProvider/UserEntityProvider.php
  src/Thought/Exception/NotSupportedThoughtException.php
  src/Thought/ThoughtfulInterface.php
  symfony.lock
  tests/Action/Image/ImageUploadActionTest.php
  tests/Action/Thought/AddThoughtActionTest.php
  tests/Metadata/Resource/Factory/AdminResourceMetadataFactoryTest.php
  tests/Security/User/JWTUserTest.php
  tests/Security/UserProvider/UserEntityProviderTest.php
  tests/Serializer/AdminContextBuilderTest.php
Labels: tests

#52 Add machine learning articles & images
  composer.lock
  src/DataFixtures/ORM/ArticleFixtures.php
  src/DataFixtures/ORM/ImageFixtures.php
  src/DataFixtures/ORM/TagFixtures.php
  src/DataFixtures/Resources/articles/000_template.yaml
  src/DataFixtures/Resources/articles/010_wstep_openai_gym.yaml
  src/DataFixtures/Resources/articles/011_qlearning-openai-gym.yaml
  src/DataFixtures/Resources/images/CartPole-environment.png
  src/DataFixtures/Resources/images/agent-learning-circle.png
  src/DataFixtures/Resources/images/frozen-lake-qlearning-card.jpeg
  src/DataFixtures/Resources/images/wstep-openai-gym-card.png
Labels: feature

#51 Move additional swagger configuration to YAML file
  composer.json
  composer.lock
  config/bundles.php
  src/DataFixtures/ORM/ArticleFixtures.php
  src/DataFixtures/ORM/CategoryFixtures.php
  src/DataFixtures/ORM/ImageFixtures.php
  src/DataFixtures/ORM/SecurityRoleFixtures.php
  src/DataFixtures/ORM/TagFixtures.php
  src/DataFixtures/ORM/UserFixtures.php
  src/DataFixtures/Resources/articles/010_wstep_openai_gym.yaml
  src/DataFixtures/Resources/articles/011_qlearning-openai-gym.yaml
  src/DataFixtures/Resources/fixtures/categories.yaml
  src/DataFixtures/Resources/fixtures/images.yaml
  src/DataFixtures/Resources/fixtures/security_roles.yaml
  src/DataFixtures/Resources/fixtures/tags.yaml
  src/DataFixtures/Resources/fixtures/users.yaml
  src/Entity/Article.php
  src/Swagger/Resources/swagger.yaml
  src/Swagger/SwaggerDocumentation.php
  symfony.lock
Labels: feature, wip
